trigger:
- main
stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: MavenPackageAndPublishArtifacts
    displayName: Maven Package and Publish Artifacts
    pool:
      Default
    steps:
    - task: Maven@3
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'pom.xml'

    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/target/*.?(war|jar)'
        TargetFolder: $(Build.ArtifactStagingDirectory)

    - upload: $(Build.ArtifactStagingDirectory)
      artifact: drop1
    
- stage: dockerBuildandpublish
  displayName: dockerbuildand publish
  jobs:
  - job: docker
    displayName: docker
    pool:
      Default
      
    steps:  
    - task: Docker@2
      inputs:
        repository: 'saivibha23'
        command: 'buildAndPush'
        Dockerfile: '**/backend/Dockerfile'
